---
driver:
  name: vagrant

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: linux
    run_list:
    - recipe[os-hardening]
    - recipe[ssh-hardening]
    verifier:
      inspec_tests:
      - url: https://github.com/dev-sec/linux-baseline
      - url: https://github.com/dev-sec/ssh-baseline
